-- SELECT NTH MAXIMUM FROM A COLUMN IN SQL --
-- SQL Server --
SELECT column_name(s) FROM TABLE
WHERE COLUMN IN (
SELECT TOP 1 COLUMN
FROM (
SELECT DISTINCT TOP (N) COLUMN
FROM COLUMN
ORDER BY COLUMN DESC
) AS RESULT
ORDER BY COLUMN);

-- MySQL --
SELECT column_name(s) FROM TABLE
WHERE COLUMN IN (
SELECT COLUMN
FROM (
SELECT DISTINCT COLUMN
FROM COLUMN
ORDER BY COLUMN DESC
  LIMIT (N)
) AS RESULT
ORDER BY COLUMN
 LIMIT 1);
